server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        - id: accountRoute
          uri: http://localhost:8080
          predicates:
           - Path=/account/**
        - id: moviesRoute
          uri: lb://MOVIE-SERVICE
          predicates:
           - Path=/movies/**
        - id: seriesRoute
          uri: lb://SERIE-SERVICE
          predicates:
           - Path=/series/**
        - id: catalogRoute
          uri: lb://CATALOG-SERVICE
          predicates:
           - Path=/catalog/**
